ci: fix sccache PDB contention on Windows (C1041)\n\nUse CMAKE_MSVC_DEBUG_INFORMATION_FORMAT=Embedded (/Z7)\ninstead of default /Zi, which causes fatal error C1041\nwhen sccache launches parallel cl.exe processes that\nall try to write the same shared .pdb file.